name: Build SMCAMDProcessor

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Download Lilu & VirtualSMC SDKs
        run: |
          mkdir -p Headers
          
          # Tải Lilu SDK
          git clone https://github.com/acidanthera/Lilu.git lilu_repo
          cp -R lilu_repo/Lilu/Headers/* ./Headers/
          curl -sL -o Lilu.zip https://github.com/acidanthera/Lilu/releases/download/1.6.7/Lilu-1.6.7-DEBUG.zip
          unzip -q Lilu.zip -d Lilu_kext
          cp -R Lilu_kext/Lilu.kext .
          
          # Tải VirtualSMC SDK
          git clone https://github.com/acidanthera/VirtualSMC.git vsmc_repo
          cp -R vsmc_repo/VirtualSMC/Headers/* ./Headers/
          curl -sL -o VirtualSMC.zip https://github.com/acidanthera/VirtualSMC/releases/download/1.3.2/VirtualSMC-1.3.2-DEBUG.zip
          unzip -q VirtualSMC.zip -d Vsmc_kext
          cp -R Vsmc_kext/Kexts/VirtualSMC.kext .

      - name: Build All Targets
        run: |
          xcodebuild -scheme AMDRyzenCPUPowerManagement -configuration Release -derivedDataPath build CODE_SIGNING_ALLOWED=NO ARCHS=x86_64
          xcodebuild -scheme SMCAMDProcessor -configuration Release -derivedDataPath build CODE_SIGNING_ALLOWED=NO ARCHS=x86_64
          xcodebuild -scheme "AMD Power Gadget" -configuration Release -derivedDataPath build CODE_SIGNING_ALLOWED=NO ARCHS=x86_64

      - name: Upload Output Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SMCAMD-Release-Files
          path: build/Build/Products/Release/
